[package]
name = "contracts"
type = "contract"
authors = [""]
compiler_version = ">=0.33.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.54.0", directory="noir-projects/aztec-nr/aztec" }
compressed_string = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.54.0", directory="noir-projects/aztec-nr/compressed-string" }
protocol_types = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.54.0", directory="noir-projects/noir-protocol-circuits/crates/types"}